export const actions = {
  user: {
    USER_DATA_FETCHING: "USER_DATA_FETCHING",
    USER_DATA_FETCHED: "USER_DATA_FETCHED",
    USER_DATA_FETCHING_ERROR: "USER_DATA_FETCHING_ERROR",
    USER_LOGGED_OUT: "USER_LOGGED_OUT",
    ALL_USER_DATA_FETCHED: "ALL_USER_DATA_FETCHED",
  },
  product: {
    PRODUCT_DATA_FETCHING: "PRODUCT_DATA_FETCHING",
    PRODUCT_DATA_FETCHED: "PRODUCT_DATA_FETCHED",
    PRODUCT_DATA_FETCHING_ERROR: "PRODUCT_DATA_FETCHING_ERROR",
    ALL_PRODUCTS_DATA_FETCHED: "ALL_PRODUCTS_DATA_FETCHED",
    ALL_CATEGORIES_DATA_FETCHED: "ALL_CATEGORIES_DATA_FETCHED",
    PRODUCTS_BY_CATEGORY_DATA_FETCHED: "PRODUCTS_BY_CATEGORY_DATA_FETCHED",
    SEARCH_PRODUCTS_DATA_FETCHED: "SEARCH_PRODUCTS_DATA_FETCHED",
  },
  cart: {
    CART_DATA_FETCHING: "CART_DATA_FETCHING",
    CART_DATA_FETCHED: "CART_DATA_FETCHED",
    CART_DATA_FETCHING_ERROR: "CART_DATA_FETCHING_ERROR",
    CLEAR_CART_DATA: "CLEAR_CART_DATA",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    UPDATE_CART_QUANTITY: "UPDATE_CART_QUANTITY",
  },
  wishlist: {
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
    REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  },
};
