export const actions = {
  user: {
    USER_DATA_FETCHING: "USER_DATA_FETCHING",
    USER_DATA_FETCHED: "USER_DATA_FETCHED",
    USER_DATA_FETCHING_ERROR: "USER_DATA_FETCHING_ERROR",
    USER_LOGGED_OUT: "USER_LOGGED_OUT",
    ALL_USER_DATA_FETCHED: "ALL_USER_DATA_FETCHED",
  },
  product: {
    PRODUCT_DATA_FETCHING: "PRODUCT_DATA_FETCHING",
    PRODUCT_DATA_FETCHED: "PRODUCT_DATA_FETCHED",
    PRODUCT_DATA_FETCHING_ERROR: "PRODUCT_DATA_FETCHING_ERROR",
    ALL_PRODUCTS_DATA_FETCHED: "ALL_PRODUCTS_DATA_FETCHED",
    ALL_CATEGORIES_DATA_FETCHED: "ALL_CATEGORIES_DATA_FETCHED",
    PRODUCTS_BY_CATEGORY_DATA_FETCHED: "PRODUCTS_BY_CATEGORY_DATA_FETCHED",
  },
  cart: {
    CART_DATA_FETCHING: "CART_DATA_FETCHING",
    CART_DATA_FETCHED: "CART_DATA_FETCHED",
    CART_DATA_FETCHING_ERROR: "CART_DATA_FETCHING_ERROR",
  },
};
