export const actions = {
  user: {
    USER_DATA_FETCHING: "USER_DATA_FETCHING",
    USER_DATA_FETCHED: "USER_DATA_FETCHED",
    USER_DATA_FETCHING_ERROR: "USER_DATA_FETCHING_ERROR",
    USER_LOGGED_OUT: "USER_LOGGED_OUT",
    ALL_USER_DATA_FETCHED: "ALL_USER_DATA_FETCHED",
  },
};
